{"name": "Login_No.002_登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_allure_demo.TestLoginMoudel object at 0x0000021AF52DF490>\n\n    @allure.story(\"登录成功\")\n    @allure.title(\"Login_No.002_登录成功\")\n    def test_login_success(self):\n        print(\"登录成功测试失败\")\n>       assert False\nE       assert False\n\ntest_allure_demo.py:15: AssertionError"}, "start": 1636897403851, "stop": 1636897403852, "uuid": "a9c60c81-9dc9-4c90-8dfc-4697938f69c7", "historyId": "6a2d2900137c956db240aed8cb9a9596", "testCaseId": "4b6ec69df0cf35b98289ec63c4355d97", "fullName": "test_allure_demo.TestLoginMoudel#test_login_success", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录成功"}, {"name": "suite", "value": "test_allure_demo"}, {"name": "subSuite", "value": "TestLoginMoudel"}, {"name": "host", "value": "DESKTOP-5N5QG51"}, {"name": "thread", "value": "10984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_demo"}]}